### ISSUE TITLE
Question about RetroArch nestopia database

### ISSUE THREAD

**Issue by joepogo** [0ldsk00l/nestopia#393]
Hey Rdanbrook, it's been a while since we've last spoke but I just recently realized that RetroArch does not allow for the use of an external nstdatabase.xml  file anymore as of 1.50. You used to could drop it in the system directory and it would override everything else. 

Apparently it's now internal only and "baked" into the core with no means to override with an external file if you want to play certain romhacks/translations, etc anymore.

I've got an xml file where over time I've added some entries to fix a bunch of games, games like contra (j) proto and crisis force demo, a smattering of some romhacks I have, wai wai world and akamojou dracula, etc and the only thing I can think of is to send it you to add to your repro since I can't use it externally anymore. (Pretty annoying)

I can't remember all of the games fixed/added but it's quite a few I've added over the years and figured other end users could benefit too. I'm sure a quick diffmerge would suffice. 

Is this feasible? As I don't know of any other way to play these games in RetroArch currently unless I'm missing something.

**Comment by rdanbrook** [comment]
One way you can do this is run the Python script in the libretro fork against your own NstDatabase.xml and rebuild. If I ever get some time, maybe I'll add an option to use the baked in one or a local copy on your filesystem...

For rom hacks, I've found the best way there is to use the IPS soft patching, so that the correct database entry and iNES header will work, then the patch is applied after the emu is all set up. Although in some cases the mapper changes when you patch...

You can also post the entries here if you want so other people can take a look at the differences. Run a diff between your NstDatabase.xml and the upstream one and then it can be looked at. I'm pretty sure some of the games you mentioned do actually work now without additional database entries.

**Comment by joepogo** [comment]
Thanks for responding buddy. Just took a few minutes and ran through my database xml file and I've added so many entries over the years that It would take me quite a while to sift through each entry so I guess I can wait until an option is added to use your own database file as that would prob be the best route. 

In some cases soft patching works but a lot of the entries I made were for mappers, translations, bootlegs, and hacks that change the mapper and causes nestopia to throw an error unless an entry is made. 

Should I change this issue to a request to be able to use an external database file for RetroArch instead? Thanks again for all you Rdanbrook.

**Comment by rdanbrook** [comment]
I'm the guy who is probably going to write that code, so no point posting it over there. I'll see if I can take care of it some day soon, but life is a rollercoaster as always.

I'd still be interested in seeing your XML database, because after some of the work done upstream I think a lot of things will just work now. Mostly thinking about stuff that needs NES 2.0 headers.

**Comment by rdanbrook** [comment]
I just sent a PR to the libretro fork for this, so once that gets merged the feature will be available in the builds they put out. I'll leave this issue open for now in case you want to post your NstDatabase.xml.

**Comment by joepogo** [comment]
Wow! That was fast! Thanks so much Rdanbrook! Yes, I'll post it up here for you shortly. In bed ATM lol but after my shift I'll put it up here for you. You can prob use some of the fixes. :)

**Comment by joepogo** [comment]
For some reason i could not attach it here so here is a temp link for ya. There are a good number of games that i've gotten working. 

I even got a mario hack to work this way, a few prototype games, and some of those pesky mapper 21, 23 games i think that always threw the dreaded unsupported mapper error. 

I do know i got the contra sample proto and crisis force proto working this way and i think parodious translation too.

I'll see if i can track down my notes for a more complete list of games. 

Thanks again for all you do man and the quick commit! 

https://tempsend.com/zwknu

**Comment by rdanbrook** [comment]
Thanks for putting that link up there. I've got the file now and I diffed it against the upstream NstDatabase.xml (which I need to sync into this repo soon).

Here's the diff, I made a gist for it: https://gist.github.com/rdanbrook/f50acc7b51d42b79496bd9ec3193a117

From what I can tell, a lot of your customizations have been fixed upstream, but there are some Konami VRC ones that could use a second look. Submappers are supported now btw, so it might be easier to just use that feature of the NES 2.0 header instead of database entries. If you can name the specific games and/or hacks that would help too.

**Comment by joepogo** [comment]
Yea, I'm going back through my notes and I'll see if I can get a more thorough list for ya shortly.

I do remember some of the 2.0 stuff fixing some of those games but they didn't fully fix games like crisis force sample and contra (j) proto as I had to add the pin wiring info in the database to get it to work correctly 100percent. Same with paradious and some others. 

I figured the more added to the database the better. 

I'll get a list here shortly for you with what I can find in my notes. 

Thanks again for what you do bro!

**Comment by joepogo** [comment]
Damn, should have kept better notes but i did find these:

Getsufuu Maden (J) [T+Eng1.0_RPGe]
 Dragon Ball Z-Kyoushuu! Saiya Jin (j) (T+eng 1.01 Red Comet)
 Bio Miracle Bokutte Upa (J) [T+Eng1.00_Vice]
 Cat Ninden Teyandee (J) [T+Eng.10_Vertigo]
 Akumajou Special - Boku Dracula-kun (J) [T+Eng1.02_Vice]
 Wai Wai World (J) [T+Eng1.00_Demiforce]
 Wai Wai World 2 - SOS!! Paseri Jou (J) [T-Eng1.00_Vice] 
 Ganbare Goemon Gaiden 2 English translation (Adventurous Translations)
 B-Wings (Eng-Trans, Stardust Crusaders, 1.0)
 Added entry for scrambled screen on some Arkanoid II roms 
 Crisis force (sample prototype, garbled without database entry)
 FIFA International 2 '96
 Crisis Force (Eng-Trans, Stardust Crusaders, 1.0 garbled without databse entry)
 Contra (Sample prototype, garbled without database entry)
 Contra (Eng-Trans, Stardust Crusaders, 1.01 (unsupported mapper without db entry)
 Keisan Game - Sansuu 2 Toshi (Eng-Trans, Pikachumanson, 1.0)
 Ganbare Goemon Gaiden (Eng-Trans, Adventurous Translations, 0.99c)
 Wai Wai World I (Eng-Trans, Dylan Robley, 1.0)
 I'm Kid Dracula (Eng-Trans, Vice Translations, 1.04)
 Parodius - From Myth to Laughter (Eng-Trans, Stardust Crusaders, 1.0)
 Twinbee 3 prototype (garbled without databse entry)
 Puzzle prototype (was garbled without entry)

Some of the ones at the top were a couple entries made by plasturion over at nesdev like back in 2011. Ill keep looking to see but as you can see a good bunch of these were in facct The VRC-2 mappers which throw unsupported mapper errors in nestopia and the ones that did work with 2.0 often loaded to scrambled screens. 

Ill keep digging.

**Comment by carmiker** [comment]
Since it is not feasible to add every revision of every VRC2/4 hack to the database, there are only two options -- modifying the header to include a submapper, or improving the heuristics in the core. I may attempt to improve the heuristics to alleviate the issue, but it likely won't completely eliminate the problem. In an ideal world, all of the hacks and translations would be updated to include the submapper upstream, but I don't see this happening, and it the old revisions would still be floating around.

**Comment by rdanbrook** [comment]
I think this issue is about as resolved as it's ever going to be, so closing.
