### ISSUE TITLE
1.53.0 narrowing error during compilation

### ISSUE THREAD

**Issue by mc1ay** [0ldsk00l/nestopia#436]
For reference:
```
Using clang, 18.1.6

CXX:        c++ -std=c++17
CXXFLAGS:   -O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing   -isystem /usr/local/include -std=c++17
CPPFLAGS:   -isystem /usr/local/include
LDFLAGS:     -fstack-protector-strong -L/usr/local/lib
```

I get 14 narrowing errors from source/core/NstStream.cpp all similar to this:
```
source/core/NstStream.cpp:317:6: error: non-constant-expression cannot be narrowed from type 'uint' (aka 'unsigned int') to 'byte' (aka 'unsigned char') in initializer list [-Wc++11-narrowing]
  317 |                                         data >> 0 & 0xFF,
      |                                         ^~~~~~~~~~~~~~~~
source/core/NstStream.cpp:317:6: note: insert an explicit cast to silence this issue
```

**Comment by carmiker** [comment]
I intend to fix these issues once I have made the emulator core pass all of the TASVideos tests, and most/all other known tests. It is annoying to see these at build time, but it is even more annoying to deal with regressions, and there are some areas of this codebase where there is a high risk for regressions.

**Comment by mc1ay** [comment]
It's FreeBSD. I'm attempting to update the port from 1.52.1 that I maintain.

**Comment by carmiker** [comment]
@mc1ay I've pushed a commit that addresses all of the narrowing issues in the emulator core. If you apply the latest commit, does this fix everything for you?

**Comment by mc1ay** [comment]
Looks like this is an issue with NstVideoFilterHqX.cpp also.

**Comment by carmiker** [comment]
I am not an autotools expert, but I did just push some changes that remove the unused filters from the FLTK build (which is now based on Nestopia JG anyway, where I removed them years ago). Does it work for you now? I will soon be ready to tag a point release, so it would be great to have all of these build fixes in for that.

**Comment by ionenwks** [comment]
> Does it work for you now?

We had been passing `-Wno-narrowing` for a while for now in Gentoo, and I am able to remove that with 1.53.1 (1.53.0 still failed if optionally using clang). Thanks.

**Comment by mc1ay** [comment]
Looks like that took care of all of the issues. The FreeBSD port should be updated soon.
